version: "3"

services: 
    voters:
        image: edgedb/edgedb:1-beta2
        # ports: 
        #     - 16419:16419
        restart: on-failure
        environment: 
            - EDGEDB_PASSWORD=test
            - EDGEDB_USER=merak
            - EDGEDB_PORT=16419
        networks: 
            - voteredge
    
    papers:
        image: edgedb/edgedb:1-beta2
        # ports: 
        #     - 16420:16420
        restart: on-failure
        environment: 
            - EDGEDB_PASSWORD=test
            - EDGEDB_USER=merak
            - EDGEDB_PORT=16420
        networks: 
            - paperedge
    
    alcor-observer:
        build:
            context: .
            network: host
            dockerfile: ./dockerfile
        restart: on-failure
        environment: 
            - URI=165.229.125.211
        ports:
            - 10001:10001
        links: 
            - voters
            - papers
        depends_on: 
            - voters
            - papers
        networks:
            - voteredge
            - paperedge

networks:
    voteredge:
    paperedge:
