# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/protobuf/capsule.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/protobuf/capsule.proto',
  package='capsule',
  syntax='proto3',
  serialized_options=b'Z\rmodel/capsule',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cproto/protobuf/capsule.proto\x12\x07\x63\x61psule\"#\n\x07\x43\x61psule\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\x0c\x42\x0fZ\rmodel/capsuleb\x06proto3'
)




_CAPSULE = _descriptor.Descriptor(
  name='Capsule',
  full_name='capsule.Capsule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='capsule.Capsule.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='capsule.Capsule.Data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Capsule'] = _CAPSULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Capsule = _reflection.GeneratedProtocolMessageType('Capsule', (_message.Message,), {
  'DESCRIPTOR' : _CAPSULE,
  '__module__' : 'proto.protobuf.capsule_pb2'
  # @@protoc_insertion_point(class_scope:capsule.Capsule)
  })
_sym_db.RegisterMessage(Capsule)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
