# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/protobuf/vote.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/protobuf/vote.proto',
  package='vote',
  syntax='proto3',
  serialized_options=b'Z\nmodel/vote',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/protobuf/vote.proto\x12\x04vote\"\x18\n\x08KeyBytes\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\"r\n\x05Paper\x12\x0f\n\x07VoterId\x18\x01 \x01(\x0c\x12\x11\n\tTimestamp\x18\x02 \x01(\x0c\x12\x0f\n\x07Message\x18\x03 \x01(\x0c\x12\x13\n\x0bRandomBytes\x18\x04 \x01(\x0c\x12\x0c\n\x04Hash\x18\x05 \x01(\x0c\x12\x11\n\tSignature\x18\x06 \x01(\x0c\"#\n\x06Result\x12\n\n\x02Ok\x18\x01 \x01(\x08\x12\r\n\x05\x45rror\x18\x02 \x01(\tB\x0cZ\nmodel/voteb\x06proto3'
)




_KEYBYTES = _descriptor.Descriptor(
  name='KeyBytes',
  full_name='vote.KeyBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Data', full_name='vote.KeyBytes.Data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=59,
)


_PAPER = _descriptor.Descriptor(
  name='Paper',
  full_name='vote.Paper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='VoterId', full_name='vote.Paper.VoterId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='vote.Paper.Timestamp', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message', full_name='vote.Paper.Message', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RandomBytes', full_name='vote.Paper.RandomBytes', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Hash', full_name='vote.Paper.Hash', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Signature', full_name='vote.Paper.Signature', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=175,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='vote.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ok', full_name='vote.Result.Ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='vote.Result.Error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['KeyBytes'] = _KEYBYTES
DESCRIPTOR.message_types_by_name['Paper'] = _PAPER
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyBytes = _reflection.GeneratedProtocolMessageType('KeyBytes', (_message.Message,), {
  'DESCRIPTOR' : _KEYBYTES,
  '__module__' : 'proto.protobuf.vote_pb2'
  # @@protoc_insertion_point(class_scope:vote.KeyBytes)
  })
_sym_db.RegisterMessage(KeyBytes)

Paper = _reflection.GeneratedProtocolMessageType('Paper', (_message.Message,), {
  'DESCRIPTOR' : _PAPER,
  '__module__' : 'proto.protobuf.vote_pb2'
  # @@protoc_insertion_point(class_scope:vote.Paper)
  })
_sym_db.RegisterMessage(Paper)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'proto.protobuf.vote_pb2'
  # @@protoc_insertion_point(class_scope:vote.Result)
  })
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
