// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/protobuf/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate string `protobuf:"bytes,1,opt,name=Candidate,proto3" json:"Candidate,omitempty"`
	Gender    bool   `protobuf:"varint,2,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Age       int32  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Region    string `protobuf:"bytes,4,opt,name=Region,proto3" json:"Region,omitempty"`
	Job       string `protobuf:"bytes,5,opt,name=Job,proto3" json:"Job,omitempty"`
	Education string `protobuf:"bytes,6,opt,name=Education,proto3" json:"Education,omitempty"`
	Married   bool   `protobuf:"varint,7,opt,name=Married,proto3" json:"Married,omitempty"`
	Divorced  bool   `protobuf:"varint,8,opt,name=Divorced,proto3" json:"Divorced,omitempty"`
	HasCar    bool   `protobuf:"varint,9,opt,name=HasCar,proto3" json:"HasCar,omitempty"`
	HouseType string `protobuf:"bytes,10,opt,name=HouseType,proto3" json:"HouseType,omitempty"`
	Salary    int32  `protobuf:"varint,11,opt,name=Salary,proto3" json:"Salary,omitempty"`
	HasDebt   bool   `protobuf:"varint,12,opt,name=HasDebt,proto3" json:"HasDebt,omitempty"`
	Ideology  string `protobuf:"bytes,13,opt,name=Ideology,proto3" json:"Ideology,omitempty"`
	VoterID   []byte `protobuf:"bytes,14,opt,name=VoterID,proto3" json:"VoterID,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protobuf_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_stats_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *Data) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *Data) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Data) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Data) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *Data) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *Data) GetMarried() bool {
	if x != nil {
		return x.Married
	}
	return false
}

func (x *Data) GetDivorced() bool {
	if x != nil {
		return x.Divorced
	}
	return false
}

func (x *Data) GetHasCar() bool {
	if x != nil {
		return x.HasCar
	}
	return false
}

func (x *Data) GetHouseType() string {
	if x != nil {
		return x.HouseType
	}
	return ""
}

func (x *Data) GetSalary() int32 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Data) GetHasDebt() bool {
	if x != nil {
		return x.HasDebt
	}
	return false
}

func (x *Data) GetIdeology() string {
	if x != nil {
		return x.Ideology
	}
	return ""
}

func (x *Data) GetVoterID() []byte {
	if x != nil {
		return x.VoterID
	}
	return nil
}

var File_proto_protobuf_stats_proto protoreflect.FileDescriptor

var file_proto_protobuf_stats_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x22, 0xea, 0x02, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x41, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x4a, 0x6f, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x1c,
	0x0a, 0x09, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x61, 0x72, 0x72, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4d,
	0x61, 0x72, 0x72, 0x69, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x76, 0x6f, 0x72, 0x63,
	0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x44, 0x69, 0x76, 0x6f, 0x72, 0x63,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x73, 0x43, 0x61, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x48, 0x61, 0x73, 0x43, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x44, 0x65, 0x62, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x48, 0x61, 0x73, 0x44, 0x65, 0x62, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x64,
	0x65, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x64,
	0x65, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x42, 0x0d, 0x5a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_protobuf_stats_proto_rawDescOnce sync.Once
	file_proto_protobuf_stats_proto_rawDescData = file_proto_protobuf_stats_proto_rawDesc
)

func file_proto_protobuf_stats_proto_rawDescGZIP() []byte {
	file_proto_protobuf_stats_proto_rawDescOnce.Do(func() {
		file_proto_protobuf_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_protobuf_stats_proto_rawDescData)
	})
	return file_proto_protobuf_stats_proto_rawDescData
}

var file_proto_protobuf_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_protobuf_stats_proto_goTypes = []interface{}{
	(*Data)(nil), // 0: stats.Data
}
var file_proto_protobuf_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_protobuf_stats_proto_init() }
func file_proto_protobuf_stats_proto_init() {
	if File_proto_protobuf_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_protobuf_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_protobuf_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_protobuf_stats_proto_goTypes,
		DependencyIndexes: file_proto_protobuf_stats_proto_depIdxs,
		MessageInfos:      file_proto_protobuf_stats_proto_msgTypes,
	}.Build()
	File_proto_protobuf_stats_proto = out.File
	file_proto_protobuf_stats_proto_rawDesc = nil
	file_proto_protobuf_stats_proto_goTypes = nil
	file_proto_protobuf_stats_proto_depIdxs = nil
}
