version: "3"

services: 
    voters:
        image: edgedb/edgedb:1-beta2
        # ports: 
        #     - 16419:16419
        restart: on-failure
        environment: 
            - EDGEDB_PASSWORD=test
            - EDGEDB_USER=merak
            - EDGEDB_PORT=16419
        networks: 
            - voteredge
    
    papers:
        image: edgedb/edgedb:1-beta2
        # ports: 
        #     - 16420:16420
        restart: on-failure
        environment: 
            - EDGEDB_PASSWORD=test
            - EDGEDB_USER=merak
            - EDGEDB_PORT=16420
        networks: 
            - paperedge

    sessions:
        image: memcached:latest
        restart: on-failure
        networks:
            - sessions

    certcodes:
        image: memcached:latest
        restart: on-failure
        networks:
            - certcodes

    keybytes:
        image: memcached:latest
        restart: on-failure
        networks:
            - keybytes

    rdb:
        image: redis:latest
        restart: on-failure
        networks:
            - rdb
    
    alcor:
        build:
            context: .
            network: host
            dockerfile: ./dockerfile
        restart: on-failure
        environment: 
            - MAX_CONNECTION=10000
            - EXPIRATION_TIME=10
            - ADMIN_PASSWORD=password
        ports:
            - 9999:9999
        links: 
            - voters
            - papers
            - sessions
            - keybytes
            - certcodes
            - rdb
        depends_on: 
            - voters
            - papers
            - sessions
            - keybytes
            - certcodes
            - rdb
        networks:
            - voteredge
            - paperedge
            - sessions
            - keybytes
            - certcodes
            - rdb

networks:
    voteredge:
    paperedge:
    sessions:
    certcodes:
    keybytes:
    rdb: