// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: protobuf/candidate.proto

package candidate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Markdown string `protobuf:"bytes,2,opt,name=Markdown,proto3" json:"Markdown,omitempty"`
	Error    string `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_candidate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_candidate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_protobuf_candidate_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Candidate) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *Candidate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CandidateList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Names []string `protobuf:"bytes,2,rep,name=Names,proto3" json:"Names,omitempty"`
}

func (x *CandidateList) Reset() {
	*x = CandidateList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_candidate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateList) ProtoMessage() {}

func (x *CandidateList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_candidate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateList.ProtoReflect.Descriptor instead.
func (*CandidateList) Descriptor() ([]byte, []int) {
	return file_protobuf_candidate_proto_rawDescGZIP(), []int{1}
}

func (x *CandidateList) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CandidateList) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_protobuf_candidate_proto protoreflect.FileDescriptor

var file_protobuf_candidate_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0x51, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f,
	0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f,
	0x77, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_candidate_proto_rawDescOnce sync.Once
	file_protobuf_candidate_proto_rawDescData = file_protobuf_candidate_proto_rawDesc
)

func file_protobuf_candidate_proto_rawDescGZIP() []byte {
	file_protobuf_candidate_proto_rawDescOnce.Do(func() {
		file_protobuf_candidate_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_candidate_proto_rawDescData)
	})
	return file_protobuf_candidate_proto_rawDescData
}

var file_protobuf_candidate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_candidate_proto_goTypes = []interface{}{
	(*Candidate)(nil),     // 0: candidate.Candidate
	(*CandidateList)(nil), // 1: candidate.CandidateList
}
var file_protobuf_candidate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_candidate_proto_init() }
func file_protobuf_candidate_proto_init() {
	if File_protobuf_candidate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_candidate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Candidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_candidate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandidateList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_candidate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_candidate_proto_goTypes,
		DependencyIndexes: file_protobuf_candidate_proto_depIdxs,
		MessageInfos:      file_protobuf_candidate_proto_msgTypes,
	}.Build()
	File_protobuf_candidate_proto = out.File
	file_protobuf_candidate_proto_rawDesc = nil
	file_protobuf_candidate_proto_goTypes = nil
	file_protobuf_candidate_proto_depIdxs = nil
}
